texts = [
	"LISTEN HERE BOY.",
	"YOU'VE CAUSED PLENTY TROUBLE TO ME.",
	"I COULD KILL YOU NOW,",
	"BUT YOUR DEADLY SKILLS HAVE CONVINCED ME\n\nOF AN ALTERNATE COURSE OF ACTION.",
	"YOUR NAME IS LORENZO?",
	"WELL, LORENZO, YOUR ACTIVITIES ARE A LITTLE BIT\n\n, SUSPICIOUS TO THE COPS NOW.",
	"AND I HAPPEN TO KNOW THAT A PERSON LIKE EMILIO WOULDN'T\n\nWANT A LIABILITY IN HIS RANKS.",
	"MAYBE YOU OUGHTA CHANGE SIDES.",
	"COME TO HIS PLACE AND SEE FOR YOURSELF.",
	"THEN MAYBE WE'LL TALK."
];