texts = [
	"ALRIGHT KID.",
	"WHATEVER YOU DO, JUST GO IN AND RELAX FIRST.",
	"TAKE A LOOK AROUND, SEE WHERE YOUR TARGETS ARE AT.",
	"THERE'S ONLY A FEW OF THEM, SO THEY WON'T POSE YOU A CHALLENGE.",
	"THE ONLY ONE I'LL WORRY ABOUT IS BIG LOUIE\n\n. HE'S THE UNDERBOSS, THAT'S THE GUY YOU'RE TAKING OUT.",
	"HE USUALLY SITS ALONE IN A PRIVATE CORNER.",
	"HE'S REAL BIG, AND JUST AS MUCH OF A MARKSMAN AS YOU ARE, \n\nSO BE CAREFUL, HE'LL TAKE A LOT OF HITS\n\nTO GO DOWN.",
	"AFTER ALL OF THAT, GET OUT."
];