texts = [
	"SEEMS LIKE YOU'VE COME IN AT A PERFECT TIME.",
	"AND I'M GUESSING THE SPADES ALREADY MOVED INTO THE CAFE.\n\nAND JUDGING BY THE LOOK ON YOUR FACE, \n\nYOU DID SOME NASTY DAMAGE TO THEM.",
	"I KNOW... AND A CERTAIN ROMEO KNOWS TOO",
	"ROMEO SEEMS TO BE PRETTY EAGER ON A WAR,\n\nBUT THE GUY JUST WOULDN'T WANT TO OPENLY DECLARE IT.",
	"LORENZO...",
	"KILL THESE TWO, THEY KILLED MY GOOD MEN. \n\nAFTER THAT, I'LL HAVE ANOTHER JOB FOR YOU.",
	"I'VE PREPARED A CAR. GO NORTH OF THE TOWN SQUARE,",
	"MY MEN WILL DRIVE YOU TO THE RED SPADES' HEADQUARTERS",
	"THEN, SNEAK INTO THEIR GARAGE AND BLOW UP ALL OF THEIR CARS!!",
	"LET THIS ACT OF REVENGE BE KNOWN TO HIM."
];