texts = [
	"LOOK AT WHAT YOU'VE DONE.",
	"BASTARD...",
	"AFTER YOUR LITTLE CRUSADE, I LIMPED ALL THE WAY\n\nTO MY CAR.",
	"BUT WHAT PURPOSE DOES ANY OF THIS SERVE?",
	"MY MEN ARE DEAD...",
	"SO IS ROMEO CONTI.",
	"AND SO IS YOUR FRIEND. YOU DID HIM NO GOOD.",
	"YOU'RE DANGEROUS...",
	"LOOK AT THIS...",
	"SEEN IT?",
	"YOU CAN PULL THE TRIGGER NOW."
];