texts = [
	"THAT WAS YOUR JOURNEY IN THE CITY OF NEW PELADO.",
	"HERE ENDETH THE LESSON.",
	"YOU WISHED THE OLD MAN A SAFE LIFE, BEFORE HE LEFT YOU TO RALLY\n\nTHE REST OF THE CITY INTO ATTACKING THE REMAINING MOB STRONGHOLDS.",
	"YOU CAN ALREADY HEAR THEIR BATTLECRY!",
	"WELL.",
	"IT'S SAFE NOW.",
	"...",
	"...",
	"A CACOPHONY OF SCREAMS RANG OUT.",
	"LOTS OF GUNFIRE AS WELL.",
	"...",
	"YOU HEAR THE OLD MAN'S VOICE, SCREAMING FOR HELP.",
	"OH NO...",
	"YOU HAVE TO HELP..."
];		