texts = [
	"THERE USED TO BE AN OTTOMAN HERE,",
	"I COULD JUST SIT DOWN, PUT MY LEGS \n\nON THAT BABY AND LET MY BRAIN GO WHEREVER IT WANTS TO.",
	"BUT THAT'S A STORY FOR ANOTHER TIME.",
	"AS YOU KNOW, I CAN'T RELAX NOW.\n\nA LOT OF THINGS HAVE BEEN HAPPENING LATELY.",
	"I'LL NEED ANOTHER JOB DONE TONIGHT.",
	"YOU'RE GONNA GO AND GET MY ORDERS IN THE TOWN SQUARE.",
	"ALRIGHT?",
	"DON'T WORRY...",
	"YOU STEP OUT OF THAT DOOR AND DO THIS JOB RIGHT\n\n, I'LL PAY YA.",
	"BEGONE."
];