texts = [
	"ALRIGHT. TIME FOR THE SPADES.",
	"ALSO WRITE THAT YOU GOT BIG LOUIE, AND SOME LEGAL FILES\n\nTHAT THEY MIGHT WANT.",
	"TELL THEM TO GO TO THE SAME PLACE.",
	"...",
	"OH, DON'T WORRY ABOUT THE RECENT HIT.",
	"THEY DON'T KNOW ABOUT ANY OF THAT.",
	"JUST GO TO THE PLACE, AND THROW THE LETTER THERE.",
	"IT'S SIMPLE. LET'S GET GOING. TO THE LEFT ALLEYWAY AGAIN."
];		