texts = [
	"WHAT DID THE BOSS TELL YOU TO DO?",
	"...",
	"HEY, THE OWNER JUST GOT NICKED.",
	"YOU KNOW?",
	"OF THE ENTIRE ESTABLISHMENT.",
	"FORK-EYE JOE DID IT FOR ROMEO'S GANG.",
	"HE KILLED MY DOG LAST WEEK. SO DO ME A FAVOUR\n\nAND GET HIM FOR ME."
];