texts = [
	"SORRY PAL, THIS CAFE'S UNDER RENOVATION RIGHT NOW.",
	"...",
	"OHHHHHHH",
	"I REMEMBER YOU!!",
	"HAHA!!",
	"SAW YOUR FACE IN A WANTED POSTER!",
	"MR MORETTI'S MAN?",
	"ALRIGHT, ALRIGHT.",
	"JUST STAND HERE ALRIGHT?",
	"HAHAHAA...",
	"BOYS!!!!!!"
];