texts = [
	"I'LL TELL YOU WHAT.",
	"THEY'VE BEEN TELLING US TO HOLD THIS PLACE FOR A LONG TIME.",
	"BUT THE COPS ARE SNEAKING AROUND NOW.\n\nTHEY'RE LOOKING FOR AN EXCUSE TO BUST US.",
	"NOW, FORK-EYE JOE INSIDE THE CAFE'S THE LOYAL ONE\n\nHE'S LOOKING TO SEE IF WE'RE MISBEHAVING",
	"HAHHHHHH...",
];