texts = [
	"I'M TIRED.",
	"FORCED INTO THIS IN THE FIRST PLACE.",
	"YOU NEW IN TOWN?",
	"THIS PLACE HAS ALWAYS BEEN WILD.",
	"ROMEO GOT HIS EYES ON ME AFTER I STRONG-ARMED THAT OLD COUPLE.",
	"THEY TRIED TO SNITCH ON US BECAUSE WE KILLED THEIR SON.",
	"I DON'T KNOW WHAT TO SAY ANYMORE JUST LIKE THEIR SON,\n\nI WAS FORCED INTO THIS.",
	"I WANT TO QUIT. MY MOM'S WORRIED SICK.\n\nMY GRANDMA...",
	"WELL... SHE DIED OF SHOCK UPON HEARING OF MY 'GREAT ACHIEVEMENTS'",
	"I'LL LIVE THE REST OF MY LIFE LIKE A SCHNOOK, IN THIS PLACE."
];