texts = [
	"I HEARD SOME GUNSHOTS IN THERE.",
	"YOU DID HIM IN?",
	"OH YEAH. YEAH, BIG LOUIE'S PRETTY MUCH DEAD.",
	"THAT'S HIS BULLET-RIDDLED CORPSE OVER THERE.",
	"WHERE NEXT?",
	"...",
	"YOU WANT TO HIT THE SPADES, AND BLOW UP THEIR CARS?",
	"ALRIGHT...",
	"THAT PLACE BRINGS UP BAD MEMORIES.",
	"GET IN THE TRUCK.",
];