texts = [
	"THAT BLOOD ON YOUR FACE...",
	"YOU'LL NEVER WASH OFF.",
	"I BET YOU TALKED TO SOME OF THE HOODS.",
	"WAIT.",
	"OHH.",
	"MY STOMACH'S GIVING....",
	"OHHH-ARRRGHHH",
	"OH MY...",
	"BAD HANGOVER.",
	"YOU HOODS...",
	"YOU DON'T UNDERSTAND HOW MUCH WE SUFFER HERE."
];