texts = [
	"HUH? EAEHAEAEFAEFASFEF...",
	"WHAT'S AEFEFA EYU.. YOUR BUSINESS HEAR?",
	"...",
	"WHAT??",
	"I HATES THOSE BALASCK SPADES  OR  AWEGTW HEATRTS OR WHATEVER",
	"WAG AWEGASEFHRARG...",
	"YOUR'REW  WOREKING OFOR HEM?",
	"WELWFLL GET MOVING!! THAEWST BIG DO OR ON THAET RIGHT THERE.",
	" YAEH WALK RIG HTR THROUGH!!!",
	"CAMONN!!!",
	"GO JOINJ THOSE RAGUYS, COMES ON KEPE THEM BUSY!!!",
	"YAEH GO  GO OG!",
	"GET LOSE!!!!!!!!!!!",
	"Y AWEH JUST BO THER ME ALL OF YA!!",
	"YA RUINE ADSMY LFIE ALL OF YAA!!!!",
	"I'LL GET YA SOMEDAY."
];